/**
 * Mock data for development and testing
 * @module lib/mock-data
 */

import type {
  LearnerProfile,
  Skill,
  Opportunity,
  Project,
  FeedItem,
  Connection,
  Credential,
  Notification,
} from "@/types"

export const mockLearnerProfile: LearnerProfile = {
  id: "1",
  email: "alex.chen@university.edu",
  name: "Alex Chen",
  avatar: "/diverse-student-portraits.png",
  role: "student",
  bio: "Computer Science student passionate about AI and full-stack development",
  location: "Freetown, Sierra Leone",
  university: "Stanford University",
  major: "Computer Science",
  graduationYear: 2025,
  skillsMatchPercentage: 83,
  verificationStatus: "verified",
  createdAt: "2023-01-15T00:00:00.000Z",
  updatedAt: new Date().toISOString(),
}

export const mockTrendingSkills: Skill[] = [
  {
    id: "1",
    name: "Quantum Skills",
    category: "technical",
    level: "advanced",
    verified: true,
    endorsements: 12,
    trending: { demandPercentage: 83, growthRate: 42, averageSalary: 1450000000, openPositions: 8934 },
  },
  {
    id: "2",
    name: "Quantum ML",
    category: "technical",
    level: "intermediate",
    verified: true,
    endorsements: 8,
    trending: { demandPercentage: 34, growthRate: 22, averageSalary: 1250000000, openPositions: 4521 },
  },
  {
    id: "3",
    name: "Distant HTML5",
    category: "technical",
    level: "expert",
    verified: true,
    endorsements: 15,
    trending: { demandPercentage: 77, growthRate: 38, averageSalary: 980000000, openPositions: 12453 },
  },
  {
    id: "4",
    name: "Contain Global",
    category: "soft-skill",
    level: "advanced",
    verified: false,
    endorsements: 5,
    trending: { demandPercentage: 35, growthRate: 15, averageSalary: 870000000, openPositions: 3421 },
  },
  {
    id: "5",
    name: "Vue Knowsp",
    category: "tools",
    level: "intermediate",
    verified: true,
    endorsements: 7,
    trending: { demandPercentage: 36, growthRate: 18, averageSalary: 1050000000, openPositions: 5672 },
  },
]

export const mockOpportunities: Opportunity[] = [
  {
    id: "1",
    title: "AI/ML Engineer Intern",
    company: "TechCorp SL",
    companyLogo: "/modern-tech-office.png",
    type: "internship",
    location: "Remote",
    remote: true,
    description: "Join our AI team building next-generation machine learning systems",
    requirements: ["Python", "TensorFlow", "2+ years experience"],
    skills: ["Python", "Machine Learning", "TensorFlow", "AI"],
    matchScore: 92,
    salary: { min: 6944444, max: 9722222, currency: "SLL" },
    postedDate: "2025-12-01T00:00:00.000Z",
    applicationUrl: "https://example.com/apply",
  },
  {
    id: "2",
    title: "Full-Stack Developer Intern",
    company: "StartupXYZ",
    companyLogo: "/abstract-startup-logo.png",
    type: "internship",
    location: "Remote",
    remote: true,
    description: "Build features for our e-commerce platform",
    requirements: ["React", "Node.js", "Currently enrolled"],
    skills: ["React", "Node.js", "TypeScript", "MongoDB"],
    matchScore: 85,
    salary: { min: 1500000, max: 2500000, currency: "SLL" },
    postedDate: "2025-12-03T00:00:00.000Z",
    applicationUrl: "https://example.com/apply",
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "AI-Powered Task Manager",
    description: "Built an intelligent task management app with ML-based priority suggestions",
    userId: "1",
    media: [
      {
        id: "1",
        type: "image",
        url: "/task-manager-app-interface.jpg",
        caption: "Main dashboard view",
      },
    ],
    skills: ["React", "Python", "Machine Learning", "Firebase"],
    collaborators: ["user-2", "user-3"],
    endorsements: [],
    verified: true,
    visibility: "public",
    startDate: "2024-09-01T00:00:00.000Z",
    endDate: "2024-11-15T00:00:00.000Z",
    githubUrl: "https://github.com/example/task-manager",
    liveUrl: "https://task-manager.example.com",
    createdAt: "2024-09-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "E-Commerce Platform",
    description: "Full-stack e-commerce application with payment integration and real-time inventory management",
    userId: "1",
    media: [
      {
        id: "2",
        type: "image",
        url: "/modern-ecommerce-dashboard.png",
        caption: "Product catalog interface",
      },
    ],
    skills: ["Next.js", "TypeScript", "Stripe", "PostgreSQL", "Prisma"],
    collaborators: ["user-4"],
    endorsements: [],
    verified: true,
    visibility: "public",
    startDate: "2024-06-01T00:00:00.000Z",
    endDate: "2024-08-30T00:00:00.000Z",
    githubUrl: "https://github.com/example/ecommerce",
    liveUrl: "https://shop.example.com",
    createdAt: "2024-06-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Social Media Analytics Dashboard",
    description: "Real-time analytics dashboard for tracking social media metrics across multiple platforms",
    userId: "1",
    media: [
      {
        id: "3",
        type: "image",
        url: "/analytics-dashboard.png",
        caption: "Analytics overview",
      },
    ],
    skills: ["React", "D3.js", "Node.js", "MongoDB", "Express"],
    collaborators: [],
    endorsements: [],
    verified: true,
    visibility: "public",
    startDate: "2024-03-15T00:00:00.000Z",
    endDate: "2024-05-20T00:00:00.000Z",
    githubUrl: "https://github.com/example/social-analytics",
    createdAt: "2024-03-15T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Mobile Fitness Tracker",
    description:
      "Cross-platform mobile app for tracking workouts, nutrition, and health metrics with AI-powered insights",
    userId: "1",
    media: [
      {
        id: "4",
        type: "image",
        url: "/fitness-tracker-mobile-app.jpg",
        caption: "Mobile app interface",
      },
    ],
    skills: ["React Native", "TensorFlow Lite", "Firebase", "GraphQL"],
    collaborators: ["user-2", "user-5"],
    endorsements: [],
    verified: false,
    visibility: "public",
    startDate: "2024-01-10T00:00:00.000Z",
    endDate: "2024-04-15T00:00:00.000Z",
    githubUrl: "https://github.com/example/fitness-tracker",
    createdAt: "2024-01-10T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Blockchain Voting System",
    description: "Decentralized voting platform ensuring transparent and secure elections using smart contracts",
    userId: "1",
    media: [
      {
        id: "5",
        type: "image",
        url: "/blockchain-voting-interface.png",
        caption: "Voting dashboard",
      },
    ],
    skills: ["Solidity", "Web3.js", "Ethereum", "React", "IPFS"],
    collaborators: ["user-6", "user-7"],
    endorsements: [],
    verified: true,
    visibility: "public",
    startDate: "2023-10-01T00:00:00.000Z",
    endDate: "2023-12-20T00:00:00.000Z",
    githubUrl: "https://github.com/example/blockchain-voting",
    createdAt: "2023-10-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Real-Time Chat Application",
    description: "Scalable chat app with end-to-end encryption, video calls, and file sharing capabilities",
    userId: "1",
    media: [
      {
        id: "6",
        type: "image",
        url: "/modern-chat-application.png",
        caption: "Chat interface",
      },
    ],
    skills: ["WebRTC", "Socket.io", "Node.js", "Redis", "Docker"],
    collaborators: ["user-3"],
    endorsements: [],
    verified: false,
    visibility: "public",
    startDate: "2024-02-01T00:00:00.000Z",
    endDate: null,
    githubUrl: "https://github.com/example/chat-app",
    liveUrl: "https://chat.example.com",
    createdAt: "2024-02-01T00:00:00.000Z",
    updatedAt: new Date().toISOString(),
  },
]

export const mockCredentials: Credential[] = [
  {
    id: "1",
    title: "AWS Certified Developer",
    issuer: "Amazon Web Services",
    issueDate: "2024-06-15T00:00:00.000Z",
    verified: true,
    blockchainHash: "0x1234...abcd",
    type: "certification",
    skills: ["AWS", "Cloud Computing", "DevOps"],
  },
  {
    id: "2",
    title: "Full-Stack Web Development",
    issuer: "Coursera",
    issueDate: "2024-03-20T00:00:00.000Z",
    verified: true,
    type: "course-completion",
    skills: ["React", "Node.js", "MongoDB", "Express"],
  },
]

export const mockConnections: Connection[] = [
  {
    id: "1",
    userId: "user-2",
    name: "Sarah Martinez",
    avatar: "/professional-woman-diverse.png",
    role: "Senior Software Engineer",
    company: "Google",
    connectionType: "mentor",
    mutualConnections: 5,
    connectedAt: "2024-08-10T00:00:00.000Z",
  },
  {
    id: "2",
    userId: "user-3",
    name: "Michael Johnson",
    avatar: "/professional-man.jpg",
    role: "Computer Science Student",
    university: "Stanford University",
    connectionType: "peer",
    mutualConnections: 12,
    connectedAt: "2024-09-15T00:00:00.000Z",
  },
  {
    id: "3",
    userId: "user-4",
    name: "Emily Chen",
    avatar: "/diverse-student-portraits.png",
    role: "Product Manager",
    company: "Meta",
    connectionType: "peer",
    mutualConnections: 8,
    connectedAt: "2024-10-05T00:00:00.000Z",
  },
  {
    id: "4",
    userId: "user-5",
    name: "James Wilson",
    avatar: "/professional-man.jpg",
    role: "Data Scientist",
    company: "Amazon",
    connectionType: "peer",
    mutualConnections: 15,
    connectedAt: "2024-09-20T00:00:00.000Z",
  },
  {
    id: "5",
    userId: "user-6",
    name: "Priya Patel",
    avatar: "/professional-woman-diverse.png",
    role: "UX Designer",
    company: "Apple",
    connectionType: "peer",
    mutualConnections: 7,
    connectedAt: "2024-11-01T00:00:00.000Z",
  },
  {
    id: "6",
    userId: "user-7",
    name: "David Kim",
    avatar: "/images.jpg",
    role: "Machine Learning Engineer",
    company: "OpenAI",
    connectionType: "mentor",
    mutualConnections: 22,
    connectedAt: "2024-08-25T00:00:00.000Z",
  },
]

export const mockSuggestedConnections = [
  {
    id: "s1",
    name: "Alexandra Rivera",
    avatar: "/professional-woman-diverse.png",
    role: "Senior AI Researcher",
    company: "DeepMind",
    matchScore: 94,
    mutualConnections: 8,
  },
  {
    id: "s2",
    name: "Marcus Thompson",
    avatar: "/professional-man.jpg",
    role: "Full Stack Developer",
    company: "Stripe",
    matchScore: 89,
    mutualConnections: 12,
  },
  {
    id: "s3",
    name: "Sophia Zhang",
    avatar: "/diverse-student-portraits.png",
    role: "Computer Science Student",
    university: "MIT",
    matchScore: 92,
    mutualConnections: 15,
  },
  {
    id: "s4",
    name: "Daniel O'Brien",
    avatar: "/images.jpg",
    role: "DevOps Engineer",
    company: "Netflix",
    matchScore: 87,
    mutualConnections: 6,
  },
  {
    id: "s5",
    name: "Aisha Mohammed",
    avatar: "/professional-woman-diverse.png",
    role: "Product Designer",
    company: "Figma",
    matchScore: 85,
    mutualConnections: 10,
  },
  {
    id: "s6",
    name: "Ryan Lee",
    avatar: "/professional-man.jpg",
    role: "Cybersecurity Analyst",
    company: "Cisco",
    matchScore: 83,
    mutualConnections: 4,
  },
  {
    id: "s7",
    name: "Maria Garcia",
    avatar: "/diverse-student-portraits.png",
    role: "Data Analyst",
    company: "Microsoft",
    matchScore: 91,
    mutualConnections: 14,
  },
  {
    id: "s8",
    name: "Kevin Nguyen",
    avatar: "/images.jpg",
    role: "Blockchain Developer",
    company: "Coinbase",
    matchScore: 88,
    mutualConnections: 9,
  },
  {
    id: "s9",
    name: "Isabella Santos",
    avatar: "/professional-woman-diverse.png",
    role: "Tech Lead",
    company: "Spotify",
    matchScore: 90,
    mutualConnections: 11,
  },
  {
    id: "s10",
    name: "Thomas Anderson",
    avatar: "/professional-man.jpg",
    role: "Software Engineer",
    company: "Tesla",
    matchScore: 86,
    mutualConnections: 7,
  },
  {
    id: "s11",
    name: "Zara Khan",
    avatar: "/diverse-student-portraits.png",
    role: "Mobile Developer",
    company: "Uber",
    matchScore: 84,
    mutualConnections: 13,
  },
  {
    id: "s12",
    name: "Jonathan Park",
    avatar: "/images.jpg",
    role: "Cloud Architect",
    company: "AWS",
    matchScore: 93,
    mutualConnections: 18,
  },
  {
    id: "s13",
    name: "Fatima Al-Sayed",
    avatar: "/professional-woman-diverse.png",
    role: "Robotics Engineer",
    company: "Boston Dynamics",
    matchScore: 89,
    mutualConnections: 5,
  },
  {
    id: "s14",
    name: "Christopher Brown",
    avatar: "/professional-man.jpg",
    role: "Game Developer",
    company: "Unity",
    matchScore: 82,
    mutualConnections: 16,
  },
  {
    id: "s15",
    name: "Yuki Tanaka",
    avatar: "/diverse-student-portraits.png",
    role: "Research Scientist",
    university: "Stanford University",
    matchScore: 95,
    mutualConnections: 20,
  },
  {
    id: "s16",
    name: "Oliver Smith",
    avatar: "/images.jpg",
    role: "Site Reliability Engineer",
    company: "Airbnb",
    matchScore: 87,
    mutualConnections: 8,
  },
  {
    id: "s17",
    name: "Nadia Ivanov",
    avatar: "/professional-woman-diverse.png",
    role: "Engineering Manager",
    company: "LinkedIn",
    matchScore: 91,
    mutualConnections: 17,
  },
  {
    id: "s18",
    name: "Carlos Rodriguez",
    avatar: "/professional-man.jpg",
    role: "Backend Developer",
    company: "Shopify",
    matchScore: 86,
    mutualConnections: 11,
  },
]

export const mockFeedItems: FeedItem[] = [
  {
    id: "1",
    type: "opportunity",
    timestamp: new Date().toISOString(),
    priority: "high",
    content: {
      title: "TechCorp is hiring Junior AI Engineer",
      description: "Vast Pembling Ta Hanevej Soeni Ml Beginner",
      image: "/generic-company-logo.png",
      data: { matchScore: 92, skillMatch: "82% match" },
    },
    actions: [{ label: "Apply Now", action: "apply", variant: "primary" }],
  },
  {
    id: "2",
    type: "skill-trending",
    timestamp: new Date().toISOString(),
    priority: "medium",
    content: {
      title: "Quantum Skills trending up 42%",
      description: "Hot in your field - 8,934 open positions",
    },
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "opportunity",
    title: "New job match: Senior Full-Stack Developer",
    message: "A position at DataCorp matches your skills at 94%. Apply now!",
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 minutes ago
    read: false,
    actionUrl: "/discover",
    icon: "briefcase",
  },
  {
    id: "n2",
    type: "connection",
    title: "Sarah Martinez accepted your connection request",
    message: "You are now connected with Sarah Martinez from Google",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    read: false,
    actionUrl: "/network",
    icon: "users",
  },
  {
    id: "n3",
    type: "skill",
    title: "Python skill verified",
    message: "Your Python skill has been verified by 3 industry professionals",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    read: true,
    actionUrl: "/profile",
    icon: "check-circle",
  },
  {
    id: "n4",
    type: "project",
    title: "Project endorsement received",
    message: "Michael Johnson endorsed your AI-Powered Task Manager project",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    read: true,
    actionUrl: "/projects",
    icon: "folder",
  },
  {
    id: "n5",
    type: "credential",
    title: "New credential added to your profile",
    message: "AWS Certified Developer credential has been verified on blockchain",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
    read: true,
    actionUrl: "/profile",
    icon: "award",
  },
  {
    id: "n6",
    type: "trending",
    title: "Quantum ML is trending in your field",
    message: "This skill has 42% growth rate with 8,934 open positions",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
    read: true,
    actionUrl: "/discover",
    icon: "trending-up",
  },
  {
    id: "n7",
    type: "connection",
    title: "You have 5 new connection suggestions",
    message: "Connect with professionals in AI and Machine Learning",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), // 4 days ago
    read: true,
    actionUrl: "/network/find",
    icon: "users",
  },
  {
    id: "n8",
    type: "opportunity",
    title: "Application deadline approaching",
    message: "Junior AI Engineer at TechCorp closes in 2 days",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 days ago
    read: true,
    actionUrl: "/discover",
    icon: "clock",
  },
]

export const MOCK_TRENDING_SKILLS = mockTrendingSkills
export const MOCK_OPPORTUNITIES = mockOpportunities

export const mockAllJobs: Opportunity[] = [
  {
    id: "j1",
    title: "AI/ML Engineer",
    company: "TechCorp SL",
    companyLogo: "/tech-company-logo.jpg",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: true,
    description:
      "Join our innovative AI team to develop cutting-edge machine learning solutions. You'll work on real-world problems, build scalable ML systems, and collaborate with talented engineers and data scientists. This role offers great opportunities for professional growth and learning.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "2+ years of experience in machine learning",
      "Strong proficiency in Python and ML frameworks",
      "Familiarity with TensorFlow or PyTorch",
      "Strong problem-solving skills",
      "Good communication and teamwork abilities",
    ],
    skills: ["Python", "Machine Learning", "TensorFlow", "AI", "Data Analysis"],
    matchScore: 92,
    salary: { min: 6944444, max: 9722222, currency: "SLL" },
    postedDate: "2025-12-01T00:00:00.000Z",
    deadline: "2026-01-15T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/ai-engineer",
  },
  {
    id: "j2",
    title: "Full-Stack Developer",
    company: "Digital Solutions SL",
    companyLogo: "/abstract-startup-logo.png",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: false,
    description:
      "We're seeking a talented full-stack developer to join our growing team. You'll be responsible for developing and maintaining web applications using modern technologies. This role offers excellent opportunities for career growth and skill development.",
    requirements: [
      "3+ years of web development experience",
      "Proficiency in React and Node.js",
      "Experience with databases (PostgreSQL, MongoDB)",
      "Understanding of RESTful APIs",
      "Version control with Git",
    ],
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "MongoDB"],
    matchScore: 88,
    salary: { min: 2500000, max: 3500000, currency: "SLL" },
    postedDate: "2025-12-05T00:00:00.000Z",
    deadline: "2026-01-20T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/fullstack",
  },
  {
    id: "j3",
    title: "Data Analyst Intern",
    company: "DataCorp SL",
    companyLogo: "/generic-company-logo.png",
    type: "internship",
    location: "Remote",
    remote: true,
    description:
      "Exciting internship opportunity for students interested in data analysis. You'll work with real-world datasets, create visualizations, and contribute to data-driven decision making. Perfect for those looking to gain hands-on experience in the data field.",
    requirements: [
      "Currently enrolled in university",
      "Basic knowledge of Python or R",
      "Understanding of statistics",
      "Familiarity with Excel or Google Sheets",
      "Strong analytical thinking",
    ],
    skills: ["Python", "Data Analysis", "Excel", "Statistics", "SQL"],
    matchScore: 85,
    salary: { min: 20833333, max: 33333333, currency: "SLL" },
    postedDate: "2025-12-03T00:00:00.000Z",
    deadline: "2026-01-10T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/data-intern",
  },
  {
    id: "j4",
    title: "Mobile App Developer",
    company: "MobileTech SL",
    companyLogo: "/tech-company-logo.jpg",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: true,
    description:
      "Join our mobile development team to create innovative iOS and Android applications. You'll work on consumer-facing apps used by thousands of users, implementing new features and ensuring optimal performance.",
    requirements: [
      "2+ years of mobile development experience",
      "Proficiency in React Native or Flutter",
      "Experience with mobile UI/UX best practices",
      "Knowledge of mobile app deployment",
      "Strong debugging skills",
    ],
    skills: ["React Native", "Flutter", "JavaScript", "Mobile Development", "UI/UX"],
    matchScore: 90,
    salary: { min: 91666667, max: 133333333, currency: "SLL" },
    postedDate: "2025-11-28T00:00:00.000Z",
    deadline: "2026-01-05T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/mobile-dev",
  },
  {
    id: "j5",
    title: "Cybersecurity Specialist",
    company: "SecureNet SL",
    companyLogo: "/abstract-startup-logo.png",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: false,
    description:
      "Protect our systems and data as a cybersecurity specialist. You'll conduct security audits, implement security measures, and respond to security incidents. This role is critical to maintaining our organization's security posture.",
    requirements: [
      "Bachelor's degree in Cybersecurity or related field",
      "3+ years of security experience",
      "Knowledge of security frameworks (ISO 27001, NIST)",
      "Experience with penetration testing",
      "Relevant certifications (CISSP, CEH) preferred",
    ],
    skills: ["Cybersecurity", "Network Security", "Penetration Testing", "Risk Assessment", "Compliance"],
    matchScore: 82,
    salary: { min: 108333333, max: 158333333, currency: "SLL" },
    postedDate: "2025-12-04T00:00:00.000Z",
    deadline: "2026-01-25T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/cybersecurity",
  },
  {
    id: "j6",
    title: "UI/UX Designer",
    company: "Creative Studios SL",
    companyLogo: "/generic-company-logo.png",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: true,
    description:
      "Design beautiful and intuitive user experiences for web and mobile applications. You'll collaborate with product managers and developers to create user-centered designs that delight our customers.",
    requirements: [
      "2+ years of UI/UX design experience",
      "Proficiency in Figma and Adobe Creative Suite",
      "Strong portfolio demonstrating design skills",
      "Understanding of user research methods",
      "Excellent communication skills",
    ],
    skills: ["Figma", "UI/UX Design", "Prototyping", "User Research", "Adobe XD"],
    matchScore: 87,
    salary: { min: 75000000, max: 116666667, currency: "SLL" },
    postedDate: "2025-12-02T00:00:00.000Z",
    deadline: "2026-01-18T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/uiux-designer",
  },
]

export const mockAllSkills: (Skill & {
  description: string
  learningPath: string[]
  relatedCourses: { title: string; provider: string; duration: string }[]
  careerOpportunities: string[]
})[] = [
  {
    id: "sk1",
    name: "Machine Learning",
    category: "technical",
    level: "advanced",
    verified: true,
    endorsements: 45,
    trending: { demandPercentage: 95, growthRate: 42, averageSalary: 1850000000, openPositions: 8934 },
    description:
      "Machine Learning is a subset of artificial intelligence that enables systems to learn and improve from experience without being explicitly programmed. It's one of the most in-demand skills in tech, with applications across industries from healthcare to finance.",
    learningPath: [
      "Learn Python programming fundamentals",
      "Study statistics and linear algebra",
      "Understand supervised and unsupervised learning",
      "Master ML algorithms and frameworks (TensorFlow, PyTorch)",
      "Work on real-world ML projects",
      "Specialize in specific ML domains (NLP, Computer Vision, etc.)",
    ],
    relatedCourses: [
      { title: "Machine Learning Specialization", provider: "Coursera", duration: "3 months" },
      { title: "Deep Learning A-Z", provider: "Udemy", duration: "22 hours" },
      { title: "Applied Machine Learning", provider: "edX", duration: "4 months" },
    ],
    careerOpportunities: [
      "Machine Learning Engineer",
      "Data Scientist",
      "AI Research Scientist",
      "ML Ops Engineer",
      "Computer Vision Engineer",
    ],
  },
  {
    id: "sk2",
    name: "React & Next.js",
    category: "technical",
    level: "advanced",
    verified: true,
    endorsements: 52,
    trending: { demandPercentage: 88, growthRate: 28, averageSalary: 1450000000, openPositions: 12453 },
    description:
      "React is a powerful JavaScript library for building user interfaces, while Next.js is a React framework that enables server-side rendering and static site generation. Together, they form a popular stack for building modern web applications.",
    learningPath: [
      "Master JavaScript and ES6+ features",
      "Learn React fundamentals (components, state, props)",
      "Understand React Hooks and Context API",
      "Study Next.js routing and data fetching",
      "Learn server-side rendering and static generation",
      "Build full-stack applications with Next.js",
    ],
    relatedCourses: [
      { title: "React - The Complete Guide", provider: "Udemy", duration: "48 hours" },
      { title: "Next.js & React", provider: "Frontend Masters", duration: "6 hours" },
      { title: "Full Stack React & Next.js", provider: "Coursera", duration: "2 months" },
    ],
    careerOpportunities: [
      "Frontend Developer",
      "Full-Stack Developer",
      "React Developer",
      "UI Engineer",
      "Web Application Developer",
    ],
  },
  {
    id: "sk3",
    name: "Cloud Architecture",
    category: "technical",
    level: "advanced",
    verified: true,
    endorsements: 38,
    trending: { demandPercentage: 85, growthRate: 35, averageSalary: 1750000000, openPositions: 5234 },
    description:
      "Cloud Architecture involves designing and implementing scalable, secure, and cost-effective cloud solutions. With businesses rapidly moving to the cloud, this skill is essential for modern infrastructure design.",
    learningPath: [
      "Understand cloud computing fundamentals",
      "Learn AWS/Azure/Google Cloud services",
      "Study cloud security and compliance",
      "Master containerization (Docker, Kubernetes)",
      "Learn infrastructure as code (Terraform)",
      "Design scalable cloud architectures",
    ],
    relatedCourses: [
      { title: "AWS Certified Solutions Architect", provider: "AWS Training", duration: "3 months" },
      { title: "Cloud Architecture with Google Cloud", provider: "Coursera", duration: "4 months" },
      { title: "Microsoft Azure Fundamentals", provider: "Microsoft Learn", duration: "2 months" },
    ],
    careerOpportunities: [
      "Cloud Architect",
      "DevOps Engineer",
      "Cloud Security Engineer",
      "Solutions Architect",
      "Site Reliability Engineer",
    ],
  },
  {
    id: "sk4",
    name: "Data Science",
    category: "technical",
    level: "advanced",
    verified: true,
    endorsements: 41,
    trending: { demandPercentage: 92, growthRate: 38, averageSalary: 1650000000, openPositions: 7621 },
    description:
      "Data Science combines statistics, programming, and domain expertise to extract insights from data. It's crucial for data-driven decision making across all industries.",
    learningPath: [
      "Learn Python and R programming",
      "Study statistics and probability",
      "Master data visualization tools",
      "Understand machine learning algorithms",
      "Learn big data technologies (Spark, Hadoop)",
      "Develop domain expertise in specific industries",
    ],
    relatedCourses: [
      { title: "Data Science Specialization", provider: "Coursera", duration: "6 months" },
      { title: "Python for Data Science", provider: "Udemy", duration: "30 hours" },
      { title: "Applied Data Science with Python", provider: "edX", duration: "5 months" },
    ],
    careerOpportunities: [
      "Data Scientist",
      "Data Analyst",
      "Business Intelligence Analyst",
      "Quantitative Analyst",
      "Research Scientist",
    ],
  },
  {
    id: "sk5",
    name: "Cybersecurity",
    category: "technical",
    level: "advanced",
    verified: true,
    endorsements: 33,
    trending: { demandPercentage: 80, growthRate: 30, averageSalary: 1550000000, openPositions: 4521 },
    description:
      "Cybersecurity professionals protect systems, networks, and data from digital attacks. With increasing cyber threats, this field offers excellent career prospects and job security.",
    learningPath: [
      "Learn networking fundamentals",
      "Study operating systems (Linux, Windows)",
      "Understand common security threats and vulnerabilities",
      "Master security tools and technologies",
      "Learn ethical hacking and penetration testing",
      "Obtain relevant certifications (CISSP, CEH, Security+)",
    ],
    relatedCourses: [
      { title: "Cybersecurity Specialization", provider: "Coursera", duration: "6 months" },
      { title: "Ethical Hacking from Scratch", provider: "Udemy", duration: "15 hours" },
      { title: "Network Security", provider: "edX", duration: "4 months" },
    ],
    careerOpportunities: [
      "Cybersecurity Analyst",
      "Penetration Tester",
      "Security Engineer",
      "Information Security Manager",
      "Security Consultant",
    ],
  },
  {
    id: "sk6",
    name: "Mobile Development",
    category: "technical",
    level: "intermediate",
    verified: true,
    endorsements: 29,
    trending: { demandPercentage: 78, growthRate: 25, averageSalary: 1350000000, openPositions: 6789 },
    description:
      "Mobile Development involves creating applications for smartphones and tablets. With billions of mobile users worldwide, skilled mobile developers are in high demand.",
    learningPath: [
      "Choose a platform (iOS, Android, or cross-platform)",
      "Learn platform-specific languages (Swift/Kotlin or React Native/Flutter)",
      "Study mobile UI/UX design principles",
      "Understand mobile app architecture",
      "Learn mobile testing and debugging",
      "Master app store deployment processes",
    ],
    relatedCourses: [
      { title: "iOS Development Bootcamp", provider: "Udemy", duration: "55 hours" },
      { title: "React Native - The Practical Guide", provider: "Udemy", duration: "35 hours" },
      { title: "Android App Development", provider: "Coursera", duration: "4 months" },
    ],
    careerOpportunities: [
      "Mobile App Developer",
      "iOS Developer",
      "Android Developer",
      "Mobile UI/UX Designer",
      "Mobile DevOps Engineer",
    ],
  },
]

export const MOCK_JOBS = [
  {
    id: "j1",
    title: "AI Engineer",
    company: "TechCorp SL",
    companyLogo: "/modern-tech-office.png",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: true,
    description:
      "We are looking for an experienced AI Engineer to join our rapidly growing team. You will be responsible for developing and deploying machine learning models that power our innovative products. You'll work with cutting-edge technologies and have the opportunity to make a significant impact on our business.",
    requirements: [
      "Bachelor's degree in Computer Science, Mathematics, or related field",
      "5+ years of experience in machine learning and AI",
      "Strong proficiency in Python and ML frameworks",
      "Familiarity with TensorFlow or PyTorch",
      "Strong problem-solving skills",
      "Good communication and teamwork abilities",
    ],
    skills: ["Python", "Machine Learning", "TensorFlow", "AI", "Data Analysis"],
    matchScore: 92,
    salary: { min: 6944444, max: 9722222, currency: "SLL" },
    postedDate: "2025-12-01T00:00:00.000Z",
    deadline: "2026-01-15T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/ai-engineer",
  },
  {
    id: "j2",
    title: "Full-Stack Developer",
    company: "Digital Solutions SL",
    companyLogo: "/abstract-startup-logo.png",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: false,
    description:
      "We're seeking a talented full-stack developer to join our growing team. You'll be responsible for developing and maintaining web applications using modern technologies. This role offers excellent opportunities for career growth and skill development.",
    requirements: [
      "3+ years of web development experience",
      "Proficiency in React and Node.js",
      "Experience with databases (PostgreSQL, MongoDB)",
      "Understanding of RESTful APIs",
      "Version control with Git",
    ],
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "MongoDB"],
    matchScore: 88,
    salary: { min: 2500000, max: 3500000, currency: "SLL" },
    postedDate: "2025-12-05T00:00:00.000Z",
    deadline: "2026-01-20T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/fullstack",
  },
  {
    id: "j3",
    title: "Data Analyst Intern",
    company: "DataCorp SL",
    companyLogo: "/generic-company-logo.png",
    type: "internship",
    location: "Remote",
    remote: true,
    description:
      "Exciting internship opportunity for students interested in data analysis. You'll work with real-world datasets, create visualizations, and contribute to data-driven decision making. Perfect for those looking to gain hands-on experience in the data field.",
    requirements: [
      "Currently enrolled in university",
      "Basic knowledge of Python or R",
      "Understanding of statistics",
      "Familiarity with Excel or Google Sheets",
      "Strong analytical thinking",
    ],
    skills: ["Python", "Data Analysis", "Excel", "Statistics", "SQL"],
    matchScore: 85,
    salary: { min: 20833333, max: 33333333, currency: "SLL" },
    postedDate: "2025-12-03T00:00:00.000Z",
    deadline: "2026-01-10T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/data-intern",
  },
  {
    id: "j4",
    title: "Mobile App Developer",
    company: "MobileTech SL",
    companyLogo: "/tech-company-logo.jpg",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: true,
    description:
      "Join our mobile development team to create innovative iOS and Android applications. You'll work on consumer-facing apps used by thousands of users, implementing new features and ensuring optimal performance.",
    requirements: [
      "2+ years of mobile development experience",
      "Proficiency in React Native or Flutter",
      "Experience with mobile UI/UX best practices",
      "Knowledge of mobile app deployment",
      "Strong debugging skills",
    ],
    skills: ["React Native", "Flutter", "JavaScript", "Mobile Development", "UI/UX"],
    matchScore: 90,
    salary: { min: 91666667, max: 133333333, currency: "SLL" },
    postedDate: "2025-11-28T00:00:00.000Z",
    deadline: "2026-01-05T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/mobile-dev",
  },
  {
    id: "j5",
    title: "Cybersecurity Specialist",
    company: "SecureNet SL",
    companyLogo: "/abstract-startup-logo.png",
    type: "job",
    location: "Freetown, Sierra Leone",
    remote: false,
    description:
      "Protect our systems and data as a cybersecurity specialist. You'll conduct security audits, implement security measures, and respond to security incidents. This role is critical to maintaining our organization's security posture.",
    requirements: [
      "Bachelor's degree in Cybersecurity or related field",
      "3+ years of security experience",
      "Knowledge of security frameworks (ISO 27001, NIST)",
      "Experience with penetration testing",
      "Relevant certifications (CISSP, CEH) preferred",
    ],
    skills: ["Cybersecurity", "Network Security", "Penetration Testing", "Risk Assessment", "Compliance"],
    matchScore: 82,
    salary: { min: 108333333, max: 158333333, currency: "SLL" },
    postedDate: "2025-12-04T00:00:00.000Z",
    deadline: "2026-01-25T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/cybersecurity",
  },
  {
    id: "j6",
    title: "UI/UX Designer",
    company: "Creative Studios SL",
    companyLogo: "/generic-company-logo.png",
    type: "job",
    location: "Remote",
    remote: true,
    description:
      "Design beautiful and intuitive user experiences for web and mobile applications. You'll collaborate with product managers and developers to create user-centered designs that delight our customers.",
    requirements: [
      "2+ years of UI/UX design experience",
      "Proficiency in Figma and Adobe Creative Suite",
      "Strong portfolio demonstrating design skills",
      "Understanding of user research methods",
      "Excellent communication skills",
    ],
    skills: ["Figma", "UI/UX Design", "Prototyping", "User Research", "Adobe XD"],
    matchScore: 87,
    salary: { min: 75000000, max: 116666667, currency: "SLL" },
    postedDate: "2025-12-02T00:00:00.000Z",
    deadline: "2026-01-18T23:59:59.000Z",
    applicationUrl: "https://example.com/apply/uiux-designer",
  },
]
