"use client"

import { useState } from "react"
import { Download, FileText, FileType } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"

interface DownloadProfileDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function DownloadProfileDialog({ open, onOpenChange }: DownloadProfileDialogProps) {
  const [format, setFormat] = useState<"pdf" | "docx">("pdf")
  const [isDownloading, setIsDownloading] = useState(false)

  const handleDownload = async () => {
    setIsDownloading(true)

    // Simulate download process
    setTimeout(() => {
      console.log(`[v0] Downloading profile as ${format.toUpperCase()}`)

      // Create a simple download link
      const element = document.createElement("a")
      const content = generateProfileContent()
      const blob = new Blob([content], {
        type:
          format === "pdf"
            ? "application/pdf"
            : "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      })
      const url = URL.createObjectURL(blob)
      element.href = url
      element.download = `profile.${format}`
      document.body.appendChild(element)
      element.click()
      document.body.removeChild(element)
      URL.revokeObjectURL(url)

      setIsDownloading(false)
      onOpenChange(false)
    }, 1500)
  }

  const generateProfileContent = () => {
    // This is a simplified version - in production, use a library like jsPDF or docx
    return `
Bridge Profile Export

John Doe
Software Engineering Student at MIT
Cambridge, MA
john.doe@email.com

BIO
Passionate software engineer with expertise in full-stack development and machine learning. 
Building innovative solutions that bridge the gap between technology and real-world problems.

WORK EXPERIENCE

Software Engineering Intern | TechCorp Inc.
May 2024 - Present | San Francisco, CA (Remote)
- Developing full-stack web applications using React, Node.js, and PostgreSQL
- Collaborated with cross-functional teams to deliver features for 50,000+ active users
Skills: React, Node.js, PostgreSQL, TypeScript

Frontend Developer | StartupXYZ
Jan 2024 - Apr 2024 | New York, NY
- Built responsive user interfaces and improved website performance by 40%
- Implemented design systems and component libraries using React and Tailwind CSS
Skills: React, Tailwind CSS, JavaScript

Research Assistant | University AI Lab
Sep 2023 - Dec 2023 | Cambridge, MA
- Conducted machine learning research focused on natural language processing
- Co-authored a paper on sentiment analysis published in peer-reviewed conference
Skills: Python, TensorFlow, NLP, Research

SKILLS

Technical Skills:
- React (95% - Expert)
- Python (88% - Advanced)
- TypeScript (85% - Advanced)
- Node.js (72% - Intermediate)

AI & Machine Learning:
- Machine Learning (82% - Advanced)
- TensorFlow (75% - Intermediate)
- PyTorch (68% - Intermediate)

Cloud & DevOps:
- AWS (80% - Advanced)
- Docker (70% - Intermediate)
- Kubernetes (45% - Beginner)

Professional Skills:
- Problem Solving (92%)
- Leadership (90%)
- Communication (88%)
- Teamwork (85%)

Generated by Bridge - Career Navigation Platform
    `.trim()
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Download Profile</DialogTitle>
          <DialogDescription>Choose the format for your professional profile export</DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <RadioGroup value={format} onValueChange={(value) => setFormat(value as "pdf" | "docx")}>
            <div className="flex items-center space-x-3 rounded-lg border p-4 transition-colors hover:bg-accent">
              <RadioGroupItem value="pdf" id="pdf" />
              <Label htmlFor="pdf" className="flex flex-1 cursor-pointer items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-red-100">
                  <FileText className="h-5 w-5 text-red-600" />
                </div>
                <div className="flex-1">
                  <div className="font-medium">PDF Document</div>
                  <div className="text-xs text-muted-foreground">Best for sharing and printing</div>
                </div>
              </Label>
            </div>

            <div className="flex items-center space-x-3 rounded-lg border p-4 transition-colors hover:bg-accent">
              <RadioGroupItem value="docx" id="docx" />
              <Label htmlFor="docx" className="flex flex-1 cursor-pointer items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-100">
                  <FileType className="h-5 w-5 text-blue-600" />
                </div>
                <div className="flex-1">
                  <div className="font-medium">Word Document</div>
                  <div className="text-xs text-muted-foreground">Editable format for customization</div>
                </div>
              </Label>
            </div>
          </RadioGroup>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isDownloading}>
            Cancel
          </Button>
          <Button onClick={handleDownload} disabled={isDownloading}>
            {isDownloading ? (
              <>
                <Download className="mr-2 h-4 w-4 animate-spin" />
                Downloading...
              </>
            ) : (
              <>
                <Download className="mr-2 h-4 w-4" />
                Download {format.toUpperCase()}
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
